[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
filterwarnings =
    ignore:.*was never imported.*:coverage.exceptions.CoverageWarning
    ignore:.*was previously imported.*:coverage.exceptions.CoverageWarning
addopts =
    --cov=src/core
    --cov=src/trackers
    --cov=src/vision_tracking
    --cov=src/analytics
    --cov=src/data
    --cov=src/detectors
    --cov=src/pipeline
    --cov-config=.coveragerc
    --cov-report=term-missing
    --cov-report=html
    -q
